### ISSUE TITLE
[voting wallet] Warn if wallet stop

### ISSUE THREAD

**Issue by vctt94** [decred/vspd#103]
Right now the vpsd won't allow to start without a dcrwallet unlocked and with `--enablevoting`. But if dcrwallet crashes or stop working for some reason, the vspd don't even warn about it.

I think it would be good having some notification for that

**Comment by jholdstock** [comment]
An error is not logged immediately when a wallet terminates because vspd does not maintain any long-lived connections with wallets.

dcrwallet is only used in the following cases:

- adding a new ticket to be voted
- changing voting preferences
- running periodic consistency checks (not yet implemented - #46)

If the wallet connection fails for any of these, then an error will be logged.

**Comment by vctt94** [comment]
But wouldn't be good to have a notification before an erro can happen? 

I noticed there is a rpc websocket connection, so I don't think it would hard to notify it. 

but if you rather, I can close this issue

**Comment by jholdstock** [comment]
I'm not saying it is a bad idea, just explaining the current situation. We can probably add a handler for the websocket closing which logs an error if the connection cannot be re-established

**Comment by vctt94** [comment]
I see, thanks for the clarification

**Comment by jholdstock** [comment]
This will be closed by #103. vspd will attempt to connect to voting wallets each time a block is found.
