### ISSUE TITLE
session not getting invalidated on logout

### ISSUE THREAD

**Issue by degeri** [decred/vspd#212]
The session is not getting invalidated when admin logs out. Hence old session is still valid.

**Comment by degeri** [comment]
I believe this is a limitation in gorilla.

**Comment by jholdstock** [comment]
Discussed this with @degeri in private and came to the following conclusions

---

This is indeed a `gorilla/sessions` limitation - specifically the fact that we are using the default cookie store. 

The potential attack vector here is request replay - an identical authentication request can be used to log into the site repeatedly. If the request is recorded (eg. user is on compromised hardware), a malicious third party can replay the request to log in elsewhere.

We [fixed this in dcrstakepool](https://github.com/decred/dcrstakepool/pull/410/files), but it required implementing our own cookiestore. The amount of code needed was non-trivial, but we decided that this was worthwhile because we were expecting members of the public to create accounts and log in to dcrstakepool. It was considered a measure to protect our users.

In the case of vspd, the only people logging in are sysadmins - people who are expected to be security conscious and not log in from insecure or public hardware. Weighing up the risk versus the additional code/complexity, I don't believe this is worth fixing in vspd.
