### ISSUE TITLE
vspinfo endpoint ideas

### ISSUE THREAD

**Issue by xaur** [decred/vspd#232]
Some ideas from looking at `vspinfo` API [response](https://ultravsp.uk/api/v3/vspinfo).

Add fields:

- `statusmessage`: server operator's custom message with a sane character limit (must fit important messages + 1-2 links)
- `votingwalletsonline` and `votingwalletstotal` could be used by automated health check crawlers
- `ticketsmissed` (dcrstakepool reported this)

Change fields:

- `vspclosed`
  - first, the code often looks a bit cleaner if booleans have positive boolean names (`...up`, `...enabled`)
  - second, a string-based enum would capture more possible statuses than just up and down. I would call it just `status`

Group ticket stats in a namespace:

- rename `voting` to `ticketslive`
- rename `revoked` to `ticketsrevoked`
- rename `voted` to `ticketsvoted`

Related: https://github.com/decred/dcrstakepool/issues/628#issuecomment-628155661

**Comment by jholdstock** [comment]
Cannot add missed tickets, see comment in #268

**Comment by jholdstock** [comment]
Your renaming suggestions do make sense, but the existing names will be kept as they are because changing them will break existing API consumers for minimal benefit.

`vspclosed` is a boolean because it has exactly two states - either the VSP is currently accepting new tickets or it is not. Perhaps `acceptingtickets` would be a better name, but I refer back to the previous point.

There is already [an endpoint](https://github.com/decred/vspd/blob/master/docs/deployment.md#voting-wallet-status) for checking voting wallet status, but it requires authenticating with the admin credentials. We could explore opening this up for public consumption, but please open a new dedicated issue for that discussion because its a slightly wider topic than just updating the `/vspinfo` endpoint.

**Comment by xaur** [comment]
Agreed re keeping the names to not break consumers. iirc I had this idea earlier but didn't submit it with good advance time before v1.0 final. Do you think it could be batched with other breaking changes, e.g. in v2.0, or will it still not worth it?

**Comment by jholdstock** [comment]
Will definitely consider it if/when a new API version is introduced. Some possible scenarios which may make a new API version necessary:

- Improving the UX for staking on Trezor (see conversation [starting here](https://matrix.to/#/!MYLcxlwzxwViTaFPGo:decred.org/$lV5bgNkNUimlwYU2JzLZEs9YJ_gpGEoVNGJ7mG7PiWw?via=decred.org&via=matrix.org&via=planetdecred.org))
- LN/multi-owner ticket purchasing as described by matheus [here](https://blog.decred.org/2019/11/11/LN-Multi-Owner-Tickets/)
- Rumoured PQ-crypto changes in a future dcrd/dcrwallet release

Closing this issue now - #272 is opened and all of the other points have been addressed. Thanks for the suggestions.
