### ISSUE TITLE
Review usage of txscript vs stdscript

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#266]
vspd uses `ExtractPkScriptAddrs` from the dcrd package `txscript` in two places

https://github.com/decred/vspd/blob/dad662b0f0e725c50f6aa095263f9ed3dccb71fc/webapi/payfee.go#L144-L151

https://github.com/decred/vspd/blob/dad662b0f0e725c50f6aa095263f9ed3dccb71fc/webapi/payfee.go#L186-L191

dcrd is adding a `stdscript` package which supersedes some elements of `txscript`. Once it is exposed, we should review whether vspd should be updated to use it.

Ref: decred/dcrd#2656

**Comment by davecgh** [comment]
For reference, `stdscript` won't have the address extraction bits, rather those will ultimately end up in `staddr` (and will use `stdscript` behind the scenes to implement it).

That said, I would personally probably reverse the logic in these cases to decode the address in question and compare the expected script and associated version directly as it would be more efficient and explicit.  e.g. something like:

```Go
addr, err := stdaddr.DecodeAddress(ticket.FeeAddress)
if err != nil {
	// handle it
}
wantScriptVer, wantScript := addr.PaymentScript()
...
for _, txOut := range feeTx.TxOut {
	if txOut.Version == wantScriptVer && bytes.Equal(txOut.PkScript, wantScript) {
		feePaid = dcrutil.Amount(txOut.Value)
		break
	}
}

if feePaid == 0 {
	// error...
}
```

In the second case for voting the voting address, you would again want to decode it, but then compare against `.VotingRightsScript()`.

There isn't really anything wrong with doing it via address extraction as it currently is either since none of it is in a hot path.  However, one thing I spotted is that it errors if not *all* of the outputs are version 0 scripts which is not really correct logic.  It doesn't matter currently really because everything is version 0, but that won't always be the case and there is nothing invalid about a transaction without different outputs using different script versions.
