### ISSUE TITLE
multi: Remove error string comparison where possible.

### ISSUE THREAD

**Issue by JoeGruffins** [decred/vspd#284]
There are several places in the code where the type of error is discerned based on the error string. This has the potential to break because an error string is not guaranteed to stay constant (afaik). It would be best to use `errors.Is/As` in the case of golang and an integer for other languages. Sometimes this is impossible, but for Decred controlled repositories, it should not be a problem. The places that I can see this occurring are as follows:

Maybe impossible to fix:
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/webapi/recovery.go#L28-L35
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/webapi/middleware.go#L28-L35

Probably fixable:
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/webapi/payfee.go#L226-L235
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/background/background.go#L217-L221
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/background/background.go#L535-L539
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/rpc/dcrd.go#L127-L155

**Comment by jholdstock** [comment]
I would love to see all of these fixed, please feel free to take it on. To give you some background as to why each of these exist:

- The code in `recovery.go` was inherited from [here](https://github.com/gin-gonic/gin/blob/master/recovery.go), added in #255. I have never tried to remove these string comparisons, so it could be possible. Perhaps the strings exist as constants somewhere in std go libs and we can re-use them.
- The secure cookie error comes from [gorilla/sessions](https://github.com/gorilla/sessions). The same kind of error handling exists in [dcrpool](https://github.com/decred/dcrpool/blob/master/gui/middleware.go#L33) (and I think other places, although I can't find any right now). I vaguely remember trying to fix this a very long time ago in dcrstakepool (before you implemented the custom cookie store). Can't recall why I exactly failed, but it's because the lib just returns a plain error with a hard-coded, inline string, which cannot be reused.
- I couldn't find a way to use errors.Is/As on the dcrwallet responses.
- `-1` is a generic error code from dcrd, used for multiple errors, so when we receive it from `sendrawtransaction` we still need to do the string comparison. Note that in the same block we are able to use errors.As for the `-40` error.

**Comment by jholdstock** [comment]
One instance of this addressed in #295

**Comment by ukane-philemon** [comment]
I looked into the error check here:
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/background/background.go#L217-L221
and here
https://github.com/decred/vspd/blob/e42b1cad330596c243baf4c391dc40c981f4de90/background/background.go#L217-L221
the error returned comes from:
https://github.com/decred/dcrwallet/blob/9a8688e60b08b68b5952bb717122669cbb3e0989/wallet/wallet.go#L496-L510
there are two possible Invalid error code return, when there is no matching agenda and no matching choice. Both error return an Invalid code 2 and when translated returns a grpc error code 3 (InvalidArgument).
vspd currently use strings.Contain() to check for only one type of error "no agenda with ID" and logs a formatted error specifically for "no agenda with ID".

**Comment by xaur** [comment]
@jholdstock if my read is right the `securecookie: the value is not valid` was exported [in 2014](https://github.com/gorilla/securecookie/commit/2cceedbccee22f41876de91a36d63ba898fde049) in response to a [similar issue](https://github.com/gorilla/securecookie/issues/6). However I'm not sure if it's safe to use because [the code](https://github.com/gorilla/securecookie/blob/22eae5c820537b29d36814c94c2c70c08e391d71/securecookie.go#L107) now says it is deprecated and may be removed in favor of other errors.

**Comment by jholdstock** [comment]
Good find, thats some deep digging for somebody who doesn't write code. That deprecation note is pretty much the reason I chose to write the test instead of just import the string.
