### ISSUE TITLE
Complete all DB operations before returning responses

### ISSUE THREAD

**Issue by jholdstock** [decred/vspd#304]
This could be a silly question (if this line means "queue" and not "send") but I'll take the beating for a chance to spot a problem.

Could there be an issue with sending success _before_ saving data to the db?

_Originally posted by @xaur in https://github.com/decred/vspd/pull/287#discussion_r744060677_

**Comment by ukane-philemon** [comment]
Yes, it is possible that saving data to db will error, and user will not be aware of this error if we send out the success message before saving data.

**Comment by itswisdomagain** [comment]
Looking through the changes in #313, it appears a good percentage of (if not all) db operations that occur after sending a response to the user are attempts to save the request and response data to db for accountability reasons iirc.

Begs the question, what's the right way to handle a scenario where the user's request is executed (e.g. vote choices are updated per a user's request) but the req/response data could not be saved?

Could return a success response despite the final db save error but the server won't be able to subsequently prove that the user actually made such a request if it became necessary to do so.

Returning an error response doesn't strike me as ideal either because the user's actual request is likely already executed and we'd be giving the user the incorrect impression that their request was not effected.

One thought is to rollback any changes that were made per the user's request if the record of the user's request cannot be saved. Or, first save the req/res data (if possible), before executing the user's request. If the req/res data cannot be saved, respond with an error. If executing the user's request fails, delete the req/res data from db. Just thoughts anyways.

**Comment by xaur** [comment]
> what's the right way to handle a scenario where the user's request is executed (e.g. vote choices are updated per a user's request) but the req/response data could not be saved?

I'd ask for whom it is a problem and who should be made aware of it. If this can somehow be problematic for the user in the future, he should hear something about it in the response. In any case it should be logged for the admin.

> first save the req/res data (if possible), before executing the user's request. If the req/res data cannot be saved, respond with an error. If executing the user's request fails, delete the req/res data from db.

I wonder if it would be a big performance hit but otherwise I like this approach the most. If the server is expected (by both the admin and the user) to save auditing info and cannot do so, it is an error.

Also, if executing the request failed, it may be useful to actually _not_ delete the req/res data to help with debugging the problem.

**Comment by ukane-philemon** [comment]
@xaur @itswisdomagain thanks for looking into this. Unlike vote choice change records, only a single alternate signing address req/resp is saved and displayed to admin after a ticket search.
I like @itswisdomagain idea. if all alternate signing address req/res are saved in db before other operation and not removed if those operations fail, a malicious user can fill admin db with failed alternate signing address req/resp. Currently this is not an issue because alternate signing address req/resp is only saved once.

Any final thoughts?

**Comment by xaur** [comment]
Oh I did not consider a malicious use case. It should not be possible to spam the db like that. Security is hard :S

Also just in case, I think the consideration when to save req/resp for accountability, how to handle the failure to save it, and what is being done in #313, applies to all db operations and not just alt signing addresses.

**Comment by jholdstock** [comment]
vspd currently stores two types of request/response - those updating vote preferences, and those adding an alternative signing address.

- [Only the 10 most recent](https://github.com/decred/vspd/blob/0fd96388cecd6506174ba9bc33d6e77d42a5fc90/database/votechange.go#L59-L66) vote pref changes are stored.
- [Only one](https://github.com/decred/vspd/blob/0fd96388cecd6506174ba9bc33d6e77d42a5fc90/webapi/setaltsignaddr.go#L63-L69) alt sign addr record is stored.

Therefore, we don't need to be concerned with malicious actors filling the database.

---

The database in this case is a local file, so realistically the only database error we expect is insufficient disk space. This should not happen to any decent sys admin with appropriate monitoring in place.

Storing the audit trail on the server is only of benefit to the sys admin and does not benefit the user in any way.

For those two reasons, I argue that if an operation is successful but storing the audit information fails, the operation should remain successful, a success response should be delivered to the user, and the sys admin should be the one to suffer. Putting the burden of retrying/recovering onto the user is not fair.

For example, if a user wants to update their voting preferences, they should be able to do so even if storing the audit fails. They should not have to try again later once the sys admin has made more added disk space.

Forcing one sys admin to deal with their own mistake is preferable to N users being forced to deal with a single sys admins (likely avoidable) problem.

**Comment by ukane-philemon** [comment]
@chappjc @xaur @itswisdomagain thanks for your feedback. After considering audit vs user, it is obvious we don't have to force user to retry because of one sys admin problem. 

This should mark this issue closed?

**Comment by jholdstock** [comment]
Yeah I think we can close this one. Anybody please feel free to re-open if you disagree or want to discuss further.
