### ISSUE TITLE
Server requirements VSPD

### ISSUE THREAD

**Issue by dabuchera** [decred/vspd#354]
Hi all,

What are the technical requirements for the vspd? Are 2 CPU, 2GB RAM and 50GB SSD enough?

Ty

**Comment by jholdstock** [comment]
That spec should be adequate, however I don't think any detailed profiling or analysis has ever been performed to determine the absolute minimums. I'd be interested to see how low we can go before things start to degrade.

Just a heads-up, the servers hosting voting wallets are much more sensitive to hardware specs as they need to issue vote transactions quickly in order to avoid being missed by miners. You can cut costs a little on the front-end server (nginx & vspd), but I wouldn't skimp on the voting wallet servers.

**Comment by dabuchera** [comment]
@jholdstock
Good to know. Thanks.
Are the specs described above sufficient for the voting servers?

**Comment by jholdstock** [comment]
Voting servers need to run both dcrd and dcrwallet. I don't know if there are documented requirements for dcrwallet, but the recommended specs for dcrd are here: https://github.com/decred/dcrd#minimum-recommended-specifications-dcrd-only

I'd probably recommend >= 3GB RAM on the voting servers to accommodate both processes. You can add some safety by configuring paging, but you don't want to be depending on that because it can slow the system down considerably.

**Comment by jholdstock** [comment]
For more info, feel free to come and chat with the devs in the development channel on https://chat.decred.org

**Comment by dabuchera** [comment]
Thanks
